### ISSUE TITLE
[1.21.11] Dedicated server crashes when resolving material simple names for compound materials

### ISSUE THREAD

**Issue by ForAnything47** [SilentChaos512/Silent-Gear#900]
## Versions

- **Silent Gear**: 4.1.6
- **Silent Lib**: 11.1.1
- **NeoForge**: 21.11.38-beta
- **Modpack**: N/A

## Expected Behavior

On a dedicated server, Silent Gear should be able to:
- craft gear made from compound materials such as alloy ingots
- recalculate existing gear data when a player logs in

Missing `.simple` translation keys should fall back safely without crashing the server or producing invalid player data.

## Actual Behavior

On a dedicated server, crafting gear from a compound material can fail with a server-side exception during gear data recalculation.

The crash is caused by `AbstractMaterial#getSimpleName` trying to use the client-only class `net.minecraft.client.resources.language.I18n` from common/server code, which results in:

`java.lang.NoClassDefFoundError: net/minecraft/client/resources/language/I18n`

I was able to reproduce this while crafting gear from an alloy ingot on a dedicated server. In an existing world, this also explains why players who already had affected Silent Gear items in their inventory/equipment could no longer join after updating to 4.1.6: the same recalculation path runs on login and fails before the player can be placed in the world.

Relevant stack path from the log:
- `AbstractMaterial.getSimpleName`
- `MaterialInstance.getSimpleName`
- `CompoundMaterialItem.getName`
- `CompoundMaterial.getDisplayName`
- `GearHelper.getItemName`
- `GearData.recalculateGearData`

## Links/Images

- Sanitized `latest.log` excerpt: https://pastebin.com/EpbQdeec

## Steps to Reproduce the Problem

1. Start a dedicated NeoForge server with Silent Gear 4.1.6.
2. Create a compound material item such as a Silent Gear alloy ingot.
3. Use that material to craft a Silent Gear tool or armor piece.
4. Observe that the server throws `NoClassDefFoundError: net/minecraft/client/resources/language/I18n` and the gear cannot be crafted.

Alternate reproduction:
1. On an older version, create and keep Silent Gear equipment made from an affected compound material.
2. Update the dedicated server to Silent Gear 4.1.6.
3. Join the server with that player.
4. Observe that gear recalculation fails on login and the player cannot be placed in the world.

**Comment by luan122** [comment]
i opened a bug report #902 but looks like this report is the same im getting

**Comment by SilentChaos512** [comment]
I believe it is. I'll get a new version with the fix in PR #901 uploaded soon.
